system/apps/catalogos/urls.py
from django.urls import path

from apps.catalogos.views import (CategoriaDel, CategoriaEdit, CategoriaNew,
                                  CategoriaView, ProductoDel, ProductoEdit,
                                  ProductoNew, ProductoView, SubCategoriaDel,
                                  SubCategoriaEdit, SubCategoriaNew,
                                  SubCategoriaView)

urlpatterns = [
    path('categorias', CategoriaView.as_view(), name='categoria_list'),
    path('categorias/new', CategoriaNew.as_view(), name='categoria_new'),
    path('categoria/edit/<int:pk>', CategoriaEdit.as_view(), name='categoria_edit'),
    path('categoria/delete/<int:pk>',
         CategoriaDel.as_view(), name='categoria_delete'),
    path('subcategorias/', SubCategoriaView.as_view(), name='subcategoria_list'),
    path('subcategorias/new', SubCategoriaNew.as_view(), name='subcategoria_new'),
    path('subcategorias/edit7<int:pk>',
         SubCategoriaEdit.as_view(), name='subcategoria_edit'),
    path('subcategoria/delete/<int:pk>',
         SubCategoriaDel.as_view(), name='subcategoria_delete'),
    path('productos', ProductoView.as_view(), name='producto_list'),
    path('productos/new', ProductoNew.as_view(), name='producto_new'),
    path('productos/edit/<int:pk>', ProductoEdit.as_view(), name='producto_edit'),
    path('productos/delete/<int:pk>',
         ProductoDel.as_view(), name='producto_delete'),
]

system/system/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

system/system_main/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include(('apps.generales.urls', 'generales'), namespace='generales')),
    path('catalogos/', include(('apps.catalogos.urls', 'catalogos'), namespace='catalogos')),
    path('facturas/', include(('apps.salidas.urls', 'salidas'), namespace="salidas")),
    path('admin/', admin.site.urls),
]

system/apps/catalogos/models.py
from apps.generales.models import ClaseModelo
from django.db import models

from tkinter.constants import CASCADE


# Create your models here.


class Categoria(ClaseModelo):

    descripcion = models.CharField(
        max_length=100, help_text='Descripción de la categoria', unique=True)

    # objects = models.Manager()

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Categoria, self).save()

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'


class SubCategoria(ClaseModelo):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    descripcion = models.CharField(
        max_length=100, help_text='Descripción de la Sub Categoria')

    def __str__(self):
        return '{}:{}'.format(self.categoria.descripcion, self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(SubCategoria, self).save()

    class Meta:
        # db_table = ''
        # managed = True
        verbose_name = 'Sub Categoria'
        verbose_name_plural = 'Sub Categorias'
        unique_together = ('categoria', 'descripcion')


class Producto(ClaseModelo):

    subcategoria = models.ForeignKey(SubCategoria, on_delete=models.CASCADE)
    descripcion = models.CharField(
        max_length=100, help_text='Descripción del Producto', unique=True)

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Producto, self).save()

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'

system/apps/catalogos/forms.py
from os.path import dirname

# from astroid import objects
from django import forms

from apps.catalogos.models import Categoria, Producto, SubCategoria


class CategoriaForm(forms.ModelForm):
    """Form definition for Categoria."""

    class Meta:
        """Meta definition for Categoriaform."""

        model = Categoria
        fields = ['descripcion', 'activo']
        labels = {'descripcion': "Descripción de la categoria",
                  'activo': "Estado"}
        widget = {'descripcion': forms.TextInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })


class SubCategoriaForm(forms.ModelForm):
    """Form definition for Categoria."""

    categoria = forms.ModelChoiceField(
        queryset=Categoria.objects.filter(activo=True).order_by('descripcion')
    )

    class Meta:
        """Meta definition for Categoriaform."""

        model = SubCategoria
        fields = ['categoria', 'descripcion', 'activo']
        labels = {
            'categoria': "Categoría",
            'descripcion': "Descripción de la sub categoria",
            'activo': "Estado"}
        widget = {'descripcion': forms.TextInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
        self.fields['categoria'].empty_label = "Seleccione Categoria"


class ProductoForm(forms.ModelForm):
    """Form definition for Categoria."""

    subcategoria = forms.ModelChoiceField(
        queryset=SubCategoria.objects.filter(
            activo=True).order_by('categoria__descripcion', 'descripcion'),
        empty_label="Selecciones Sub Categoria"
    )

    class Meta:
        """Meta definition for Categoriaform."""

        model = Producto
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

system/apps/catalogos/views.py
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from apps.catalogos.forms import CategoriaForm, ProductoForm, SubCategoriaForm
from apps.catalogos.models import Categoria, Producto, SubCategoria
from apps.generales.views import SinPrivilegios


class CategoriaView(LoginRequiredMixin, generic.ListView):
    model = Categoria
    template_name = "catalogos/categoria_list.html"
    context_object_name = "obj"
    login_url = 'generales:login'


class CategoriaNew(SuccessMessageMixin, LoginRequiredMixin, SinPrivilegios,
                   generic.CreateView):
    permission_required = "catalogos.add_categoria"
    model = Categoria
    template_name = "catalogos/categoria_form.html"
    context_object_name = 'obj'
    form_class = CategoriaForm
    success_url = reverse_lazy("catalogos:categoria_list")
    success_message = "Categoría Creada Satisfactoriamente"


class CategoriaEdit(LoginRequiredMixin, SinPrivilegios, generic.UpdateView):
    permission_required = "catalogos.change_categoria"
    model = Categoria
    template_name = "catalogos/categoria_form.html"
    context_object_name = 'obj'
    form_class = CategoriaForm
    success_url = reverse_lazy("catalogos:categoria_list")


class CategoriaDel(LoginRequiredMixin, SinPrivilegios, generic.DeleteView):
    permission_required = "catalogos.delete_categoria"
    model = Categoria
    template_name = "catalogos/catalogos_del.html"
    context_object_name = 'obj'
    success_url = reverse_lazy("catalogos:categoria_list")


class SubCategoriaView(LoginRequiredMixin, generic.ListView):
    model = SubCategoria
    template_name = "catalogos/subcategoria_list.html"
    context_object_name = "obj"
    login_url = 'generales:login'


class SubCategoriaNew(SuccessMessageMixin, LoginRequiredMixin, SinPrivilegios,
                      generic.CreateView):
    permission_required = "catalogos.add_subcategoria"
    model = SubCategoria
    template_name = "catalogos/subcategoria_form.html"
    context_object_name = 'obj'
    form_class = SubCategoriaForm
    success_url = reverse_lazy("catalogos:subcategoria_list")
    success_message = "Sub Categoría Creada Satisfactoriamente"


class SubCategoriaEdit(SuccessMessageMixin, LoginRequiredMixin, SinPrivilegios, generic.UpdateView):
    permission_required = "catalogos.change_subcategoria"
    model = SubCategoria
    template_name = "catalogos/subcategoria_form.html"
    context_object_name = 'obj'
    form_class = SubCategoriaForm
    success_url = reverse_lazy("catalogos:subcategoria_list")
    success_message = "Sub Categoría Actualizada Satisfactoriamente"


class SubCategoriaDel(LoginRequiredMixin, SinPrivilegios, generic.DeleteView):
    permission_required = "catalogos.delete_subcategoria"
    model = SubCategoria
    template_name = "catalogos/catalogos_del.html"
    context_object_name = 'obj'
    success_url = reverse_lazy("catalogos:subcategoria_list")


class ProductoView(LoginRequiredMixin, generic.ListView):
    model = Producto
    template_name = "catalogos/producto_list.html"
    context_object_name = "obj"
    login_url = 'generales:login'


class ProductoNew(SuccessMessageMixin, LoginRequiredMixin, SinPrivilegios,
                  generic.CreateView):
    permission_required = "catalogos.add_producto"
    model = Producto
    template_name = "catalogos/producto_form.html"
    context_object_name = 'obj'
    form_class = ProductoForm
    success_url = reverse_lazy("catalogos:producto_list")
    success_message = "Producto Creado Satisfactoriamente"


class ProductoEdit(SuccessMessageMixin, LoginRequiredMixin, SinPrivilegios, generic.UpdateView):
    permission_required = "catalogos.change_producto"
    model = Producto
    template_name = "catalogos/producto_form.html"
    context_object_name = 'obj'
    form_class = ProductoForm
    success_url = reverse_lazy("catalogos:producto_list")
    success_message = "Producto Modificado Satisfactoriamente"


class ProductoDel(LoginRequiredMixin, SinPrivilegios, generic.DeleteView):
    permission_required = "catalogos.delete_producto"
    model = Producto
    template_name = "catalogos/productos_del.html"
    context_object_name = 'obj'
    success_url = reverse_lazy("catalogos:producto_list")

system/apps/catalogos/templates/catalogos/catalogos_del.html
{% extends 'base/base.html' %}
{% block contenido %}
<form method="POST">
    <div class="panel panel-default">
        <div class="panel-heading">
            Eliminar
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
            {% csrf_token %}
            <div class="alert alert-success">
                ¿Eliminar {{ obj.descripcion }} ?
            </div>
            <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Si, Eliminar</button>
            <a href="{% url 'catalogos:categoria_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
        </div>
    </div>
</form>
{% endblock contenido %}

system/apps/catalogos/templates/catalogos/categoria_form.html
{% extends 'base/base.html' %}

{% block contenido %}
<form method="POST">
    <div class="panel-heading">
        Editar/Crear Categoria
    </div>
    <div class="panel-body">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
        <a href="{% url 'catalogos:categoria_list' %}" class="btn btn-success"> Cancelar</a>
    </div>
</form>
{% endblock contenido %}

system/apps/catalogos/templates/catalogos/categoria_list.html
{% extends 'base/base.html' %}
{% block contenido %}
<div class="panel panel-primary">
    <div class="panel-heading">
        <a href="{% url 'catalogos:categoria_new' %}" class="btn btn-info"> <span class="fa fa-plus-circle"></span>
            Nueva</a>
    </div>
    <div class="panel-body">
        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Descripción</th>
                    <th>Estado</th>
                    <th>Creado</th>
                    <th>Modificado</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.descripcion }}</td>
                    <td>{{ item.activo|yesno:"Activo, Inactivo" }}</td>
                    <td>{{ item.creado|date:'d/m/Y H:i' }}</td>
                    <td>{{ item.modificado|date:'d/m/Y H:i' }}</td>
                    <td>
                        <a href="{% url 'catalogos:categoria_edit' item.id %}" class="btn btn-primary btn-circle"><span
                                class="fa fa-edit"></span></a>
                        <a href="{% url 'catalogos:categoria_delete' item.id %}" class="btn btn-danger btn-circle"><span
                                class="fa fa-trash"></span></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock contenido %}

system/apps/catalogos/templates/catalogos/producto_form.html
{% extends 'base/base.html' %}
{% block contenido %}
<form method="POST">
    <div class="panel panel-default">
        <div class="panel-heading">
            Editar/Crear Producto
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
            {% csrf_token %}
            <div class="form-group has-success">
                <label class="control-label" for="inputSuccess">Categoria</label>
                {{ form.subcategoria }}
            </div>
            <div class="form-group has-warning">
                <label class="control-label" for="inputWarning">Descricion</label>
                {{ form.descripcion }}
            </div>
            <div class="form-group has-error">
                <label class="control-label" for="inputError">Estado</label>
                {{ form.activo }}
            </div>
            <button type="submit" class="btn btn-danger">
                <span class="fa fa-save"></span> Guardar
            </button>
            <a href="{% url 'catalogos:producto_list' %}" class="btn btn-success">
                <span class="fa fa-undo"></span> Cancelar
            </a>
        </div>
    </div>
</form>
{% endblock contenido %}

system/apps/catalogos/templates/catalogos/producto_list.html
{% extends 'base/base.html' %}
{% block contenido %}
<div class="panel panel-primary">
    <div class="panel-heading">
        <a href="{% url 'catalogos:producto_new' %}" class="btn btn-info"> <span class="fa fa-plus-circle"></span>
            Nueva</a>
    </div>
    <div class="panel-body">
        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Sub Categoria</th>
                    <th>Descripción</th>
                    <th>Estado</th>
                    <th>Creado</th>
                    <th>Modificado</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.subcategoria }}</td>
                    <td>{{ item.descripcion }}</td>
                    <td>{{ item.activo|yesno:"Activo, Inactivo" }}</td>
                    <td>{{ item.creado|date:'d/m/Y H:i' }}</td>
                    <td>{{ item.modificado|date:'d/m/Y H:i' }}</td>
                    <td>
                        <a href="{% url 'catalogos:producto_edit' item.id %}" class="btn btn-primary btn-circle"><span
                                class="fa fa-edit"></span></a>
                        <a href="{% url 'catalogos:producto_delete' item.id %}" class="btn btn-danger btn-circle"><span
                                class="fa fa-trash"></span></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock contenido %}

system/apps/catalogos/templates/catalogos/productos_del.html
{% extends 'base/base.html' %}
{% block contenido %}
<form method="POST">
    <div class="panel panel-default">
        <div class="panel-heading">
            Eliminar
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
            {% csrf_token %}
            <div class="alert alert-success">
                ¿Eliminar {{ obj.descripcion }} ?
            </div>
            <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Si, Eliminar</button>
            <a href="{% url 'catalogos:producto_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
        </div>
    </div>
</form>
{% endblock contenido %}

system/apps/catalogos/templates/catalogos/subcategoria_form.html
{% extends 'base/base.html' %}

{% block contenido %}
<form method="POST">
    <div class="panel-heading">
        Editar/Crear Sub Categoria
    </div>
    <div class="panel-body">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
        <a href="{% url 'catalogos:subcategoria_list' %}" class="btn btn-success"> Cancelar</a>
    </div>
</form>
{% endblock contenido %}

system/apps/catalogos/templates/catalogos/subcategoria_list.html
{% extends 'base/base.html' %}
{% block contenido %}
<div class="panel panel-primary">
    <div class="panel-heading">
        <a href="{% url 'catalogos:subcategoria_new' %}" class="btn btn-info"> <span class="fa fa-plus-circle"></span>
            Nueva</a>
    </div>
    <div class="panel-body">
        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Categoria</th>
                    <th>Descripción</th>
                    <th>Estado</th>
                    <th>Creado</th>
                    <th>Modificado</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.categoria }}</td>
                    <td>{{ item.descripcion }}</td>
                    <td>{{ item.activo|yesno:"Activo, Inactivo" }}</td>
                    <td>{{ item.creado|date:'d/m/Y H:i' }}</td>
                    <td>{{ item.modificado|date:'d/m/Y H:i' }}</td>
                    <td>
                        <a href="{% url 'catalogos:subcategoria_edit' item.id %}" class="btn btn-primary btn-circle"><span
                                class="fa fa-edit"></span></a>
                        <a href="{% url 'catalogos:categoria_delete' item.id %}" class="btn btn-danger btn-circle"><span
                                class="fa fa-trash"></span></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock contenido %}