system/apps/generales/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .views import Home, HomeSinPrivilegios

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='generales/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='generales/login.html'), name='logout'),
    path('sin_privilegios/', HomeSinPrivilegios.as_view(), name='sin_privilegios')
]

system/system/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

system/system_main/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include(('apps.generales.urls', 'generales'), namespace='generales')),
    path('catalogos/', include(('apps.catalogos.urls', 'catalogos'), namespace='catalogos')),
    path('facturas/', include(('apps.salidas.urls', 'salidas'), namespace="salidas")),
    path('admin/', admin.site.urls),
]

system/apps/generales/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

# Create your models here.


class ClaseModelo(models.Model):
    activo = models.BooleanField(default=True)
    creado = models.DateTimeField(auto_now_add=True)
    modificado = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True
        verbose_name = _("Clase Modelo")
        verbose_name_plural = _("Clases Modelo")

    def __str__(self):
        return '{}'.format(self.activo)

system/apps/generales/views.py
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.http import HttpResponse, HttpResponseRedirect
# from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic


# Create your views here.
class SinPrivilegios(PermissionRequiredMixin):
    login_url = 'generales:sin_privilegios'
    raise_exception = False
    redirect_field_name = "redirecto_to"

    def handle_no_permission(self):
        return HttpResponseRedirect(reverse_lazy(self.login_url))


class HomePage(generic.View):
    def get(self, request, *args, **kwargs):
        return HttpResponse('Pagina de inicio')

    def post(self, request, *args, **kwargs):
        return HttpResponse('POST request!')


class Home(LoginRequiredMixin, generic.TemplateView):
    template_name = "generales/home.html"
    login_url = 'generales:login'


class HomeSinPrivilegios(generic.TemplateView):
    template_name = "generales/sin_privilegios.html"

system/apps/generales/templates/generales/home.html
{% extends 'base/base.html' %}

{% block head_block %}Home{% endblock head_block %}

{% block contenido %}Bienvenidos a home{% endblock contenido %}

system/apps/generales/templates/generales/login.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Login - Facturación</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'base/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{% static 'base/vendor/metisMenu/metisMenu.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'base/dist/css/sb-admin-2.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'base/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Login</h3>
                        <small class="text-danger">
                            {% if form.errors %}
                            {% for field in form %}
                            {% if field.errors %}
                            {% for error in field.errors %}
                            {{ error|escape }}
                            {% endfor %}
                            {% endif %}
                            {% endfor %}
                            {% if form.non_field_errors%}
                            {% for error in form.non_field_errors %}
                            {{ error|escape }}
                            {% endfor %}
                            {% endif %}
                            {% endif %}
                        </small>
                    </div>
                    <div class="panel-body">
                        <form method="POST">
                            {% csrf_token %}
                            <fieldset>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Username" name="username" type="text" id="id_username"
                                        autofocus>
                                </div>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Password" name="password" type="password"
                                        id="id_password" value="">
                                </div>
                                <!-- Change this to a button or input when using this as a form -->
                                <button type="submit" class="btn btn-lg btn-success btn-block">Login</button>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- jQuery -->
    <script src="{% static 'base/vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'base/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{% static 'base/vendor/metisMenu/metisMenu.min.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'base/dist/js/sb-admin-2.js' %}"></script>
</body>

</html>

system/apps/generales/templates/generales/sin_privilegios.html
{% extends 'base/base.html' %}
{% block contenido %}
<div class="col-lg-8">
    <div class="panel panel-primary">
        <div class="panel-heading">
            Sin privilegios necesarios
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <h4 class="text-danger text-center">{{ user.username|upper }}
                        <mark>no tiene suficientes privilegios</mark> para cargar la opción solicitada.
                        <br>
                        <small>Para poder acceder, debes loguearte con un usuario con privilegios necesarios.</small>
                    </h4>
                    <br>
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <a href="{{request.META.HTTP_REFERER}}" class="btn btn-info">
                <span class="fa fa-thumbs-up"></span> Ok, Continuar</a>
            <a href="{% url 'generales:logout' %}" class="btn btn-warning">
                <span class="fa fa-user-secret"></span> Ingresar con otro Usuario</a>
        </div>
    </div>
</div>
{% endblock contenido %}