system/apps/salidas/urls.py
from django.urls import path

from .views import FacturaList, FacturaNew, FacturaEdit, FacturaDel

urlpatterns = [
    path('facturas', FacturaList.as_view(), name='factura_list'),
    path('factura/new', FacturaNew.as_view(), name="factura_new"),
    path('factura/edit/<int:pk>', FacturaEdit.as_view(), name="factura_edit"),
    path('factura/delete/<int:pk>', FacturaDel.as_view(), name="factura_delete")
]

system/system/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

system/system_main/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include(('apps.generales.urls', 'generales'), namespace='generales')),
    path('catalogos/', include(('apps.catalogos.urls', 'catalogos'), namespace='catalogos')),
    path('facturas/', include(('apps.salidas.urls', 'salidas'), namespace="salidas")),
    path('admin/', admin.site.urls),
]

system/apps/salidas/models.py
from decimal import Decimal

from django.db import models

from apps.catalogos.models import Producto
from apps.generales.models import ClaseModelo


class FacturaEnc(ClaseModelo):
    fecha_factura = models.DateField()
    observacion = models.CharField(max_length=200, null=True,
                                   blank=True)

    def __str__(self):
        return '{}'.format(self.fecha_factura)

    class Meta:
        verbose_name_plural = "Encabezados de Facturas"
        verbose_name = "Encabezado de Factura"


class FacturaDet(ClaseModelo):
    factura = models.ForeignKey(FacturaEnc, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField(default=0)
    precio = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    total = models.DecimalField(max_digits=5, decimal_places=2, default=0)

    def __str__(self):
        return '{}-{}'.format(self.factura, self.producto)

    def save(self):
        self.total = Decimal(self.cantidad) * Decimal(self.precio)
        super(FacturaDet, self).save()

    class Meta:
        verbose_name_plural = "Detalles de Facturas"
        verbose_name = "Detalle de Factura"

system/apps/salidas/forms.py
from django import forms

from django.forms.models import inlineformset_factory

from apps.salidas.models import FacturaEnc, FacturaDet
from apps.catalogos.models import Producto


class FacturaEncForm(forms.ModelForm):
    fecha_factura = forms.DateInput()

    class Meta:
        model = FacturaEnc
        fields = ['fecha_factura', 'observacion']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })


class FacturaDetForm(forms.ModelForm):
    producto = forms.ModelChoiceField(
        queryset=Producto.objects.filter(activo=True).
        order_by("descripcion"),
        empty_label="Seleccione Producto"
    )

    class Meta:
        model = FacturaDet
        fields = ['producto', 'cantidad', 'precio', 'total']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
        self.fields['total'].widget.attrs['readonly'] = True

    def clean_cantidad(self):
        cantidad = self.cleaned_data["cantidad"]
        if not cantidad:
            raise forms.ValidationError("Cantidad Requerida")
        elif cantidad <= 0:
            raise forms.ValidationError("Cantidad Incorrecta")
        return cantidad

    def clean_precio(self):
        precio = self.cleaned_data["precio"]
        if not precio:
            raise forms.ValidationError("Precio Requerido")
        if precio <= 0:
            raise forms.ValidationError("Precio Incorrecto")
        return precio


DetalleFacturaFormSet = inlineformset_factory(
    FacturaEnc, FacturaDet, form=FacturaDetForm, extra=3)

system/apps/salidas/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from apps.generales.views import SinPrivilegios

from apps.salidas.forms import DetalleFacturaFormSet, FacturaDetForm, FacturaEncForm
from .models import FacturaDet, FacturaEnc


class FacturaList(LoginRequiredMixin, generic.ListView):
    login_url = 'generales:login'
    model = FacturaEnc
    template_name = "salidas/facturas_list.html"
    context_object_name = "facturas"


class FacturaNew(LoginRequiredMixin, SinPrivilegios, generic.CreateView):
    permission_required = 'salidas.add_facturaenc'
    model = FacturaEnc
    login_url = 'generales:home'
    template_name = 'salidas/factura_form.html'
    form_class = FacturaEncForm
    success_url = reverse_lazy('salidas:factura_list')

    def get(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        detalle_factura_formset = DetalleFacturaFormSet()
        return self.render_to_response(
            self.get_context_data(
                form=form,
                detalle_factura=detalle_factura_formset
            )
        )

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        detalle_factura = DetalleFacturaFormSet(request.POST)

        if form.is_valid() and detalle_factura.is_valid():
            return self.form_valid(form, detalle_factura)
        else:
            return self.form_invalid(form, detalle_factura)

    def form_valid(self, form, detalle_factura):
        self.object = form.save()
        detalle_factura.instance = self.object
        detalle_factura.save()
        return HttpResponseRedirect(self.success_url)

    def form_invalid(self, form, detalle_factura):
        return self.render_to_response(
            self.get_context_data(
                form=form,
                detalle_factura=detalle_factura
            )
        )


class FacturaEdit(SinPrivilegios, generic.UpdateView):
    permission_required = 'salidas.change_facturaenc'
    model = FacturaEnc
    login_url = 'generales:home'
    template_name = 'salidas/factura_form.html'
    form_class = FacturaEncForm
    success_url = reverse_lazy('salidas:factura_list')

    def get_success_url(self):
        from django.urls import reverse
        return reverse('salidas:factura_edit',
                       kwargs={'pk': self.get_object().id})

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        detalles = FacturaDet.objects.filter(
            factura=self.object).order_by('pk')
        detalles_data = []
        for detalle in detalles:
            d = {
                'producto': detalle.producto,
                'cantidad': detalle.cantidad,
                'precio': detalle.precio,
                'total': detalle.total
            }
            detalles_data.append(d)

        detalle_factura = DetalleFacturaFormSet(initial=detalles_data)
        detalle_factura.extra += len(detalles_data)
        return self.render_to_response(
            self.get_context_data(
                form=form,
                detalle_factura=detalle_factura
            )
        )

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        detalle_factura = DetalleFacturaFormSet(request.POST)
        if form.is_valid() and detalle_factura.is_valid():
            return self.form_valid(form, detalle_factura)
        else:
            return self.form_invalid(form, detalle_factura)

    def form_valid(self, form, detalle_factura):
        self.object = form.save()
        detalle_factura.instance = self.object
        FacturaDet.objects.filter(factura=self.object).delete()
        detalle_factura.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, detalle_factura):
        return self.render_to_response(
            self.get_context_data(
                form=form,
                detalle_factura=detalle_factura
            )
        )


class FacturaDel(SinPrivilegios, generic.DeleteView):
    permission_required = "salidas:delete_facturaenc"
    model = FacturaEnc
    template_name = "salidas/factura_del.html"
    context_object_name = 'obj'
    success_url = reverse_lazy("salidas:factura_list")

system/apps/salidas/templates/salidas/factura_del.html
{% extends 'base/base.html' %}
{% block contenido %}
<form method="POST">
    <div class="panel panel-default">
        <div class="panel-heading">
            Eliminar
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
            {% csrf_token %}
            <div class="alert alert-success">
                ¿Eliminar Factura {{ obj.id }} con fecha {{ obj.fecha_factura|date:'d/m/Y' }} ?
            </div>
            <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Si, Eliminar</button>
            <a href="{% url 'salidas:factura_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
        </div>
    </div>
</form>
{% endblock contenido %}

system/apps/salidas/templates/salidas/factura_form.html
{% extends 'base/base.html' %}
{% block contenido%}
{% if form.errors %}
{% for field in form %}
{% if field.errors %}
<div class="alert alert-danger fade in">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    {% for error in field.errors %}
    <strong>{{ error|escape }}</strong>
    {% endfor %}
</div>
{% endif %}
{% endfor %}
{% if form.non_field_errors%}
<div class="alert alert-danger">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    {% for error in form.non_field_errors %}

    <strong>{{ error|escape }}</strong>
    {% endfor %}
</div>
{% endif %}
{% endif %}

{% if object %}
<form method="POST" action="{% url 'salidas:factura_edit' object.pk %}">
    {% else %}
    <form method="POST" action="{% url 'salidas:factura_new' %}">
        {% endif %}
        <div class="panel panel-red">
            <div class="panel-heading">
                {% if object %} Editar {% else %} Nueva {% endif %} Factura
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                {% csrf_token %}
                <div class="col-md-6">
                    <div class="form-group has-success">
                        <label class="control-label" for="inputSuccess">Fecha</label>
                        {{ form.fecha_factura }}
                        <small class="text-danger">{{form.errors.fecha_factura}}</small>
                        {% if form.fecha_factura.errors %}
                        {% for error in form.fecha_factura.errors %}
                        <small class="text-danger">{{ error|escape }} </small>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group has-success">
                        <label class="control-label" for="inputSuccess">Observaciones</label>
                        {{ form.observacion }}
                        <small class="text-danger">{{form.errors.observacion}}</small>
                    </div>
                </div>
                {{ detalle_factura.management_form }}
                <table class="table">
                    <thead>
                        <td class="text-center">Producto</td>
                        <td class="text-center">Cantidad</td>
                        <td class="text-center">Precio</td>
                        <td class="text-center">Total</td>
                        <td class="text-center">Borrar</td>
                    </thead>
                    <tbody>
                        {% for detalle in detalle_factura %}
                        <tr>
                            <td>{{ detalle.producto }}</td>
                            <td> {{ detalle.cantidad }}
                                {% if detalle.cantidad.errors %}
                                {% for error in detalle.cantidad.errors %}
                                <small class="text-danger">{{ error|escape }} </small>
                                {% endfor %}
                                {% endif %}
                            </td>
                            <td>
                                {{ detalle.precio }}
                                {% if detalle.precio.errors %}
                                {% for error in detalle.precio.errors %}
                                <small class="text-danger">{{ error|escape }} </small>
                                {% endfor %}
                                {% endif %}
                            </td>
                            <td> {{ detalle.total }} </td>
                            <td>{{ detalle.DELETE }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="panel-footer">
                <div class="text-center">
                    <button type="submit" class="btn btn-social-icon btn-danger" name="submit"><i class="fa fa-save"></i>
                        Guardar</button>
                    <a class="btn btn-social-icon btn-warning" href="{% url 'salidas:factura_list' %}"><i class="fa fa-times"></i>
                        Cancelar</a>
                </div>
            </div>
        </div>
    </form>
    {% endblock contenido%}

system/apps/salidas/templates/salidas/facturas_list.html
{% extends 'base/base.html' %}
{% block contenido %}
<div class="panel panel-default">
    <div class="panel-heading">
        <a href="{% url 'salidas:factura_new' %}" class="btn btn-info">
            <span class="fa fa-plus-circle"></span> Nueva Factura
        </a>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead>
                <tr>
                    <th>No. Fact</th>
                    <th>Fecha Fact.</th>
                    <th>Observacion</th>
                    <th>Estado</th>
                    <th>Creado</th>
                    <th>Modificado</th>
                    <th class="all">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for item in facturas %}
                <tr>
                    <td>{{item.id}}</td>
                    <td>{{item.fecha_factura|date:'d/m/Y'}}</td>
                    <td>{{item.observacion}}</td>
                    <td>{{item.activo|yesno:"Activo,Inactivo"}}</td>
                    <td>{{item.creado|date:'d/m/Y H:i'}}</td>
                    <td>{{item.modificado|date:'d/m/Y H:i'}}</td>
                    <td>
                        <a href="{% url 'salidas:factura_edit' item.id %}" class="btn btn-primary btn-circle">
                            <span class="fa fa-edit"></span>
                        </a>
                        <a href="{% url 'salidas:factura_delete' item.id %}" class="btn btn-danger btn-circle">
                            <span class="fa fa-trash"></span>
                        </a>
                    </td>
                </tr>
                {% endfor%}
            </tbody>
        </table>
    </div>
</div>
{% endblock contenido%}